project:
  type: website

website:
  title: "Data Science Notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/DominikVogel
      - icon: twitter
        href: https://twitter.com/DrDominikVogel
  open-graph: true
  twitter-card: true
format:
  html:
    theme: cosmo
    css: styles.css



